# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 596bd01f00b779dce6401a420721d5d8635e1c3909de0179a961e5a6c9bd270c54d3a6ab2e7df5e073bbb41c737bedb1560f98dbd7dec8cb279c953bf8eff6af

test:
  secret_key_base: 444b5041e57a297f79577aeab9648996db21898ec50ce327063846313e553a5c45548eba6f2058ac7bca8a4115e2dbdf5f31245292572b0beab6c979f2c5f23c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
